**Data set start 100 rows of accept and reject**

**LOADING DATASET**

In [3]:
import numpy as np
import pandas as pd

In [4]:
accepted_list = pd.read_csv('data/accepted_2007_to_2018Q4.csv')
rejected_list = pd.read_csv('data/rejected_2007_to_2018Q4.csv')

C:\Users\mitansh\AppData\Local\Temp\ipykernel_14244\2105560673.py:1: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  accepted_list = pd.read_csv('data/accepted_2007_to_2018Q4.csv')

**INSPECTING DATASET**

**ACCEPTED**

In [5]:
for i, col in enumerate(accepted_list.columns, 1):
    print(f"{i}. {col}")

1. id
2. member_id
3. loan_amnt
4. funded_amnt
5. funded_amnt_inv
6. term
7. int_rate
8. installment
9. grade
10. sub_grade
11. emp_title
12. emp_length
13. home_ownership
14. annual_inc
15. verification_status
16. issue_d
17. loan_status
18. pymnt_plan
19. url
20. desc
21. purpose
22. title
23. zip_code
24. addr_state
25. dti
26. delinq_2yrs
27. earliest_cr_line
28. fico_range_low
29. fico_range_high
30. inq_last_6mths
31. mths_since_last_delinq
32. mths_since_last_record
33. open_acc
34. pub_rec
35. revol_bal
36. revol_util
37. total_acc
38. initial_list_status
39. out_prncp
40. out_prncp_inv
41. total_pymnt
42. total_pymnt_inv
43. total_rec_prncp
44. total_rec_int
45. total_rec_late_fee
46. recoveries
47. collection_recovery_fee
48. last_pymnt_d
49. last_pymnt_amnt
50. next_pymnt_d
51. last_credit_pull_d
52. last_fico_range_high
53. last_fico_range_low
54. collections_12_mths_ex_med
55. mths_since_last_major_derog
56. policy_code
57. application_type
58. annual_inc_joint
59. dti_joint
60. verification_status_joint
61. acc_now_delinq
62. tot_coll_amt
63. tot_cur_bal
64. open_acc_6m
65. open_act_il
66. open_il_12m
67. open_il_24m
68. mths_since_rcnt_il
69. total_bal_il
70. il_util
71. open_rv_12m
72. open_rv_24m
73. max_bal_bc
74. all_util
75. total_rev_hi_lim
76. inq_fi
77. total_cu_tl
78. inq_last_12m
79. acc_open_past_24mths
80. avg_cur_bal
81. bc_open_to_buy
82. bc_util
83. chargeoff_within_12_mths
84. delinq_amnt
85. mo_sin_old_il_acct
86. mo_sin_old_rev_tl_op
87. mo_sin_rcnt_rev_tl_op
88. mo_sin_rcnt_tl
89. mort_acc
90. mths_since_recent_bc
91. mths_since_recent_bc_dlq
92. mths_since_recent_inq
93. mths_since_recent_revol_delinq
94. num_accts_ever_120_pd
95. num_actv_bc_tl
96. num_actv_rev_tl
97. num_bc_sats
98. num_bc_tl
99. num_il_tl
100. num_op_rev_tl
101. num_rev_accts
102. num_rev_tl_bal_gt_0
103. num_sats
104. num_tl_120dpd_2m
105. num_tl_30dpd
106. num_tl_90g_dpd_24m
107. num_tl_op_past_12m
108. pct_tl_nvr_dlq
109. percent_bc_gt_75
110. pub_rec_bankruptcies
111. tax_liens
112. tot_hi_cred_lim
113. total_bal_ex_mort
114. total_bc_limit
115. total_il_high_credit_limit
116. revol_bal_joint
117. sec_app_fico_range_low
118. sec_app_fico_range_high
119. sec_app_earliest_cr_line
120. sec_app_inq_last_6mths
121. sec_app_mort_acc
122. sec_app_open_acc
123. sec_app_revol_util
124. sec_app_open_act_il
125. sec_app_num_rev_accts
126. sec_app_chargeoff_within_12_mths
127. sec_app_collections_12_mths_ex_med
128. sec_app_mths_since_last_major_derog
129. hardship_flag
130. hardship_type
131. hardship_reason
132. hardship_status
133. deferral_term
134. hardship_amount
135. hardship_start_date
136. hardship_end_date
137. payment_plan_start_date
138. hardship_length
139. hardship_dpd
140. hardship_loan_status
141. orig_projected_additional_accrued_interest
142. hardship_payoff_balance_amount
143. hardship_last_payment_amount
144. disbursement_method
145. debt_settlement_flag
146. debt_settlement_flag_date
147. settlement_status
148. settlement_date
149. settlement_amount
150. settlement_percentage
151. settlement_term

In [6]:
pd.set_option('display.max_rows', None)
accepted_list.head(100)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
5,68426831,NaN,11950.0,11950.0,11950.0,36 months,13.44,405.18,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
6,68476668,NaN,20000.0,20000.0,20000.0,36 months,9.17,637.58,B,B2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
7,67275481,NaN,20000.0,20000.0,20000.0,36 months,8.49,631.26,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
8,68466926,NaN,10000.0,10000.0,10000.0,36 months,6.49,306.45,A,A2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
9,68616873,NaN,8000.0,8000.0,8000.0,36 months,11.48,263.74,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
10,68356421,NaN,22400.0,22400.0,22400.0,60 months,12.88,508.30,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
11,68426545,NaN,16000.0,16000.0,16000.0,60 months,12.88,363.07,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
12,68338832,NaN,1400.0,1400.0,1400.0,36 months,12.88,47.10,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
13,66624733,NaN,18000.0,18000.0,18000.0,60 months,19.48,471.70,E,E2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
14,68466961,NaN,28000.0,28000.0,28000.0,36 months,6.49,858.05,A,A2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
15,68354783,NaN,9600.0,9600.0,9600.0,36 months,7.49,298.58,A,A4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
16,68466916,NaN,25000.0,25000.0,25000.0,36 months,7.49,777.55,A,A4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
17,68577849,NaN,18000.0,18000.0,18000.0,60 months,11.99,400.31,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
18,68506798,NaN,23000.0,23000.0,23000.0,60 months,8.49,471.77,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
19,68495092,NaN,8650.0,8650.0,8650.0,36 months,19.89,320.99,E,E3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
20,68566886,NaN,29900.0,29900.0,29900.0,60 months,12.88,678.49,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
21,68009401,NaN,16000.0,16000.0,16000.0,60 months,14.85,379.39,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
22,68476702,NaN,28000.0,28000.0,28000.0,36 months,13.44,949.38,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
23,68436666,NaN,5000.0,5000.0,5000.0,36 months,13.44,169.54,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
24,68476715,NaN,6000.0,6000.0,6000.0,36 months,7.49,186.61,A,A4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
25,67849662,NaN,4225.0,4225.0,4225.0,36 months,14.85,146.16,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
26,68596180,NaN,20000.0,20000.0,20000.0,36 months,5.32,602.30,A,A1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
27,68526907,NaN,16000.0,16000.0,16000.0,60 months,17.97,406.04,D,D4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
28,68607141,NaN,17600.0,17600.0,17600.0,36 months,5.32,530.03,A,A1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
29,68526883,NaN,15000.0,15000.0,15000.0,36 months,5.32,451.73,A,A1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
30,67715283,NaN,16000.0,16000.0,16000.0,36 months,12.88,538.18,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
31,68341789,NaN,24250.0,24250.0,24250.0,60 months,24.24,701.01,F,F3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
32,68533595,NaN,12000.0,12000.0,12000.0,36 months,10.78,391.62,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
33,68415473,NaN,25000.0,25000.0,25000.0,60 months,13.99,581.58,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
34,68537655,NaN,16800.0,16800.0,16800.0,60 months,12.88,381.23,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
35,68446769,NaN,7000.0,7000.0,7000.0,36 months,7.49,217.72,A,A4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
36,68367011,NaN,21000.0,21000.0,21000.0,60 months,13.99,488.53,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
37,68407301,NaN,27500.0,27500.0,27500.0,60 months,14.85,652.06,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
38,68356614,NaN,7200.0,7200.0,7200.0,36 months,11.48,237.36,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
39,68426865,NaN,20000.0,20000.0,20000.0,36 months,14.85,691.84,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
40,68476676,NaN,20000.0,20000.0,20000.0,36 months,15.77,700.88,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
41,68566951,NaN,10000.0,10000.0,10000.0,60 months,17.97,253.78,D,D4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
42,68615044,NaN,16000.0,16000.0,16000.0,60 months,13.99,372.21,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
43,68527009,NaN,20000.0,20000.0,20000.0,36 months,9.80,643.47,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
44,68547583,NaN,8650.0,8650.0,8650.0,36 months,5.32,260.50,A,A1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
45,68587709,NaN,21000.0,21000.0,21000.0,60 months,13.44,482.56,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
46,68446771,NaN,7200.0,7200.0,7200.0,36 months,15.77,252.32,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
47,66796130,NaN,8800.0,8800.0,8800.0,36 months,9.80,283.13,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
48,68617034,NaN,14650.0,14650.0,14650.0,60 months,20.50,392.23,E,E4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
49,68387134,NaN,2500.0,2500.0,2500.0,36 months,17.27,89.47,D,D3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
50,68566925,NaN,11000.0,11000.0,11000.0,36 months,9.17,350.67,B,B2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
51,68516838,NaN,23850.0,23850.0,23850.0,60 months,17.27,596.21,D,D3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
52,68476697,NaN,15700.0,15700.0,15700.0,60 months,16.59,386.74,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
53,68566856,NaN,28800.0,28800.0,28800.0,60 months,11.99,640.50,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
54,68543413,NaN,10000.0,10000.0,10000.0,36 months,12.88,336.37,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
55,68366663,NaN,24000.0,24000.0,24000.0,60 months,9.80,507.58,B,B3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
56,68416916,NaN,28000.0,28000.0,28000.0,60 months,18.49,718.51,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
57,68444620,NaN,35000.0,35000.0,35000.0,60 months,11.99,778.38,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
58,68082535,NaN,7200.0,7200.0,7200.0,36 months,9.17,229.53,B,B2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
59,68466995,NaN,10000.0,10000.0,10000.0,36 months,7.91,312.95,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
60,68584507,NaN,16000.0,16000.0,16000.0,60 months,13.44,367.67,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
61,68466924,NaN,21875.0,21875.0,21875.0,36 months,11.99,726.46,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
62,68367009,NaN,14025.0,14025.0,14025.0,60 months,18.49,359.90,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
63,68475450,NaN,35000.0,35000.0,35000.0,60 months,12.88,794.21,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
64,68525943,NaN,20000.0,20000.0,20000.0,36 months,12.88,672.73,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
65,68340446,NaN,14000.0,14000.0,14000.0,60 months,14.85,331.96,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
66,68615169,NaN,16000.0,16000.0,16000.0,60 months,8.49,328.19,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
67,68397043,NaN,28000.0,28000.0,28000.0,60 months,14.85,663.92,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
68,68506862,NaN,20000.0,20000.0,20000.0,60 months,13.99,465.27,C,C4,...,NaN,NaN,Cash,Y,Nov-2017,COMPLETE,Sep-2017,9915.0,55.00,1.0
69,68341799,NaN,17600.0,17600.0,17600.0,60 months,19.89,465.22,E,E3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
70,68487261,NaN,4200.0,4200.0,4200.0,36 months,13.44,142.41,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
71,68597047,NaN,19000.0,19000.0,19000.0,60 months,14.85,450.52,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
72,68366999,NaN,15850.0,15850.0,15850.0,60 months,23.13,448.01,F,F2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
73,68506885,NaN,10000.0,10000.0,10000.0,60 months,11.99,222.40,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
74,68394562,NaN,30000.0,30000.0,30000.0,36 months,15.77,1051.31,D,D1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
75,68416953,NaN,1500.0,1500.0,1500.0,36 months,6.49,45.97,A,A2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
76,68587652,NaN,25000.0,25000.0,25000.0,36 months,5.32,752.87,A,A1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
77,68407333,NaN,16250.0,16250.0,16250.0,60 months,13.44,373.41,C,C3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
78,68466066,NaN,20200.0,20200.0,20200.0,60 months,18.49,518.35,D,D5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
79,68436934,NaN,23975.0,23975.0,23975.0,60 months,19.89,633.73,E,E3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
80,68617057,NaN,15000.0,15000.0,15000.0,60 months,10.78,324.50,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
81,68536799,NaN,10000.0,10000.0,10000.0,36 months,10.78,326.35,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
82,68357012,NaN,15000.0,15000.0,15000.0,36 months,8.49,473.45,B,B1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
83,68376217,NaN,23100.0,23100.0,23100.0,60 months,20.50,618.46,E,E4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
84,68526942,NaN,27300.0,27300.0,27300.0,36 months,17.27,977.00,D,D3,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
85,68396080,NaN,25000.0,25000.0,25000.0,60 months,11.48,549.57,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
86,68385794,NaN,15000.0,15000.0,15000.0,36 months,10.78,489.52,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
87,68374676,NaN,10000.0,10000.0,10000.0,60 months,16.59,246.33,D,D2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
88,68547679,NaN,18500.0,18500.0,18500.0,60 months,12.88,419.80,C,C2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
89,68537594,NaN,5000.0,5000.0,5000.0,36 months,7.91,156.48,A,A5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
90,68565856,NaN,9000.0,9000.0,9000.0,36 months,9.17,286.92,B,B2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
91,68367006,NaN,11000.0,11000.0,11000.0,36 months,6.49,337.09,A,A2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
92,68426699,NaN,20000.0,20000.0,20000.0,36 months,6.49,612.89,A,A2,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
93,68377020,NaN,15000.0,15000.0,15000.0,36 months,5.32,451.73,A,A1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
94,68446746,NaN,12000.0,12000.0,12000.0,36 months,5.32,361.38,A,A1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
95,68537564,NaN,8000.0,8000.0,8000.0,36 months,10.78,261.08,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
96,68446784,NaN,12000.0,12000.0,12000.0,36 months,10.78,391.62,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
97,68376533,NaN,18000.0,18000.0,18000.0,36 months,7.49,559.83,A,A4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
98,68476714,NaN,3600.0,3600.0,3600.0,36 months,11.48,118.68,B,B5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
99,66615254,NaN,7200.0,7200.0,7200.0,36 months,17.27,257.67,D,D3,...,NaN,NaN,Cash,Y,May-2018,BROKEN,Nov-2017,2761.0,50.01,10.0

**REJECTED**

In [7]:
for i, col in enumerate(rejected_list.columns, 1):
    print(f"{i}. {col}")

1. Amount Requested
2. Application Date
3. Loan Title
4. Risk_Score
5. Debt-To-Income Ratio
6. Zip Code
7. State
8. Employment Length
9. Policy Code

In [8]:
pd.set_option('display.max_rows', None)
rejected_list.head(20)

,Amount Requested,Application Date,Loan Title,Risk_Score,Debt-To-Income Ratio,Zip Code,State,Employment Length,Policy Code
0,1000.0,2007-05-26,Wedding Covered but No Honeymoon,693.0,10%,481xx,NM,4 years,0.0
1,1000.0,2007-05-26,Consolidating Debt,703.0,10%,010xx,MA,< 1 year,0.0
2,11000.0,2007-05-27,Want to consolidate my debt,715.0,10%,212xx,MD,1 year,0.0
3,6000.0,2007-05-27,waksman,698.0,38.64%,017xx,MA,< 1 year,0.0
4,1500.0,2007-05-27,mdrigo,509.0,9.43%,209xx,MD,< 1 year,0.0
5,15000.0,2007-05-27,Trinfiniti,645.0,0%,105xx,NY,3 years,0.0
6,10000.0,2007-05-27,NOTIFYi Inc,693.0,10%,210xx,MD,< 1 year,0.0
7,3900.0,2007-05-27,For Justin.,700.0,10%,469xx,IN,2 years,0.0
8,3000.0,2007-05-28,title?,694.0,10%,808xx,CO,4 years,0.0
9,2500.0,2007-05-28,timgerst,573.0,11.76%,407xx,KY,4 years,0.0
10,3900.0,2007-05-28,need to consolidate,710.0,10%,705xx,LA,10+ years,0.0
11,1000.0,2007-05-28,sixstrings,680.0,10%,424xx,KY,1 year,0.0
12,3000.0,2007-05-28,bmoore5110,688.0,10%,190xx,PA,< 1 year,0.0
13,1500.0,2007-05-28,MHarkins,704.0,10%,189xx,PA,3 years,0.0
14,1000.0,2007-05-28,Moving,694.0,10%,354xx,AL,< 1 year,0.0
15,8000.0,2007-05-28,Recent College Grad Wants to Pay Off CCs,708.0,10%,374xx,TN,< 1 year,0.0
16,12000.0,2007-05-29,FoundersCafe.com,685.0,10%,770xx,TX,3 years,0.0
17,1000.0,2007-05-29,UChicago2004,698.0,10%,207xx,MD,3 years,0.0
18,15000.0,2007-05-29,Cancer is Killing My Credit,680.0,10%,432xx,OH,< 1 year,0.0
19,5000.0,2007-05-29,2006-2007 College Debt Loan,680.0,10%,011xx,MA,< 1 year,0.0

In [9]:
pd.set_option('display.max_rows', None)

accepted_list.isnull().sum()

id                                                  0
member_id                                     2260701
loan_amnt                                          33
funded_amnt                                        33
funded_amnt_inv                                    33
term                                               33
int_rate                                           33
installment                                        33
grade                                              33
sub_grade                                          33
emp_title                                      167002
emp_length                                     146940
home_ownership                                     33
annual_inc                                         37
verification_status                                33
issue_d                                            33
loan_status                                        33
pymnt_plan                                         33
url                                                33
desc                                          2134636
purpose                                            33
title                                           23359
zip_code                                           34
addr_state                                         33
dti                                              1744
delinq_2yrs                                        62
earliest_cr_line                                   62
fico_range_low                                     33
fico_range_high                                    33
inq_last_6mths                                     63
mths_since_last_delinq                        1158535
mths_since_last_record                        1901545
open_acc                                           62
pub_rec                                            62
revol_bal                                          33
revol_util                                       1835
total_acc                                          62
initial_list_status                                33
out_prncp                                          33
out_prncp_inv                                      33
total_pymnt                                        33
total_pymnt_inv                                    33
total_rec_prncp                                    33
total_rec_int                                      33
total_rec_late_fee                                 33
recoveries                                         33
collection_recovery_fee                            33
last_pymnt_d                                     2460
last_pymnt_amnt                                    33
next_pymnt_d                                  1345343
last_credit_pull_d                                105
last_fico_range_high                               33
last_fico_range_low                                33
collections_12_mths_ex_med                        178
mths_since_last_major_derog                   1679926
policy_code                                        33
application_type                                   33
annual_inc_joint                              2139991
dti_joint                                     2139995
verification_status_joint                     2144971
acc_now_delinq                                     62
tot_coll_amt                                    70309
tot_cur_bal                                     70309
open_acc_6m                                    866163
open_act_il                                    866162
open_il_12m                                    866162
open_il_24m                                    866162
mths_since_rcnt_il                             909957
total_bal_il                                   866162
il_util                                       1068883
open_rv_12m                                    866162
open_rv_24m                                    866162
max_bal_bc                                     866162
all_util                                       866381
total_rev_hi_lim                                70309
inq_fi                                         866162
total_cu_tl                                    866163
inq_last_12m                                   866163
acc_open_past_24mths                            50063
avg_cur_bal                                     70379
bc_open_to_buy                                  74968
bc_util                                         76104
chargeoff_within_12_mths                          178
delinq_amnt                                        62
mo_sin_old_il_acct                             139104
mo_sin_old_rev_tl_op                            70310
mo_sin_rcnt_rev_tl_op                           70310
mo_sin_rcnt_tl                                  70309
mort_acc                                        50063
mths_since_recent_bc                            73445
mths_since_recent_bc_dlq                      1741000
mths_since_recent_inq                          295468
mths_since_recent_revol_delinq                1520342
num_accts_ever_120_pd                           70309
num_actv_bc_tl                                  70309
num_actv_rev_tl                                 70309
num_bc_sats                                     58623
num_bc_tl                                       70309
num_il_tl                                       70309
num_op_rev_tl                                   70309
num_rev_accts                                   70310
num_rev_tl_bal_gt_0                             70309
num_sats                                        58623
num_tl_120dpd_2m                               153690
num_tl_30dpd                                    70309
num_tl_90g_dpd_24m                              70309
num_tl_op_past_12m                              70309
pct_tl_nvr_dlq                                  70464
percent_bc_gt_75                                75412
pub_rec_bankruptcies                             1398
tax_liens                                         138
tot_hi_cred_lim                                 70309
total_bal_ex_mort                               50063
total_bc_limit                                  50063
total_il_high_credit_limit                      70309
revol_bal_joint                               2152681
sec_app_fico_range_low                        2152680
sec_app_fico_range_high                       2152680
sec_app_earliest_cr_line                      2152680
sec_app_inq_last_6mths                        2152680
sec_app_mort_acc                              2152680
sec_app_open_acc                              2152680
sec_app_revol_util                            2154517
sec_app_open_act_il                           2152680
sec_app_num_rev_accts                         2152680
sec_app_chargeoff_within_12_mths              2152680
sec_app_collections_12_mths_ex_med            2152680
sec_app_mths_since_last_major_derog           2224759
hardship_flag                                      33
hardship_type                                 2249784
hardship_reason                               2249784
hardship_status                               2249784
deferral_term                                 2249784
hardship_amount                               2249784
hardship_start_date                           2249784
hardship_end_date                             2249784
payment_plan_start_date                       2249784
hardship_length                               2249784
hardship_dpd                                  2249784
hardship_loan_status                          2249784
orig_projected_additional_accrued_interest    2252050
hardship_payoff_balance_amount                2249784
hardship_last_payment_amount                  2249784
disbursement_method                                33
debt_settlement_flag                               33
debt_settlement_flag_date                     2226455
settlement_status                             2226455
settlement_date                               2226455
settlement_amount                             2226455
settlement_percentage                         2226455
settlement_term                               2226455
dtype: int64

In [10]:
rejected_list.isnull().sum()

Amount Requested               0
Application Date               0
Loan Title                  1305
Risk_Score              18497630
Debt-To-Income Ratio           0
Zip Code                     293
State                         22
Employment Length         951355
Policy Code                  918
dtype: int64

In [11]:
%pip install sweetviz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sweetviz in c:\users\mitansh\appdata\roaming\python\python313\site-packages (2.3.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in c:\programdata\anaconda3\lib\site-packages (from sweetviz) (2.3.3)
Requirement already satisfied: numpy>=1.16.0 in c:\programdata\anaconda3\lib\site-packages (from sweetviz) (2.3.5)
Requirement already satisfied: matplotlib>=3.1.3 in c:\programdata\anaconda3\lib\site-packages (from sweetviz) (3.10.6)
Requirement already satisfied: tqdm>=4.43.0 in c:\programdata\anaconda3\lib\site-packages (from sweetviz) (4.67.1)
Requirement already satisfied: scipy>=1.3.2 in c:\programdata\anaconda3\lib\site-packages (from sweetviz) (1.16.3)
Requirement already satisfied: jinja2>=2.11.1 in c:\programdata\anaconda3\lib\site-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib_resources>=1.2.0 in c:\users\mitansh\appdata\roaming\python\python313\site-packages (from sweetviz) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2>=2.11.1->sweetviz) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (25.0)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm>=4.43.0->sweetviz) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

**VISUALIZATION**

In [12]:
import sweetviz as sv

In [13]:
row_count_acc = accepted_list.shape[0]
print(f"Number of rows: {row_count_acc}")

Number of rows: 2260701

In [14]:
row_count_rej = rejected_list.shape[0]
print(f"Number of rows: {row_count_rej}")

Number of rows: 27648741

In [15]:
accepted_list["loan_status"].value_counts(dropna=False)

loan_status
Fully Paid                                             1076751
Current                                                 878317
Charged Off                                             268559
Late (31-120 days)                                       21467
In Grace Period                                           8436
Late (16-30 days)                                         4349
Does not meet the credit policy. Status:Fully Paid        1988
Does not meet the credit policy. Status:Charged Off        761
Default                                                     40
NaN                                                         33
Name: count, dtype: int64